import { chromium } from '@playwright/test';
const base = process.env.PAPERCLIP_URL || 'http://127.0.0.1:5199';
const browser = await chromium.launch({ headless: true, executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', args: ['--disable-gpu', '--use-gl=swiftshader', '--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
page.setDefaultTimeout(10000);
const errors=[];
page.on('console', m => { if (m.type()==='error') errors.push(m.text()); });
page.on('pageerror', e => errors.push(e.message));
await page.goto(`${base}/TYL/knowledge-graph`, { waitUntil: 'domcontentloaded', timeout: 15000 }).catch(e => console.log(JSON.stringify({ step:'goto-timeout-nonfatal', message:e.message.slice(0,200) })));
await page.waitForTimeout(6000);
const state = await page.evaluate(() => ({ ready: document.readyState, text: document.body.innerText, buttons: Array.from(document.querySelectorAll('button')).map(b => b.textContent?.trim() || ''), canvases: document.querySelectorAll('canvas').length })).catch(e => ({ error: e.message }));
console.log(JSON.stringify({ step:'dom-state', url: page.url(), ready: state.ready, textSample: (state.text||'').slice(0,500), buttons: state.buttons, canvases: state.canvases, error: state.error }));
if (!state.buttons?.some(b => /Fleet KB/i.test(b))) throw new Error('Fleet KB button not visible in brain view');
if (state.buttons?.some(b => /Entity Graph/i.test(b))) throw new Error('Entity Graph button still visible');
if ((state.canvases ?? 0) < 1) throw new Error('No canvas rendered for FleetBrainView');
await page.getByRole('button', { name: /Fleet KB/i }).first().click();
await page.waitForTimeout(3000);
const kb = await page.evaluate(() => ({ text: document.body.innerText, placeholders: Array.from(document.querySelectorAll('input')).map(i => i.getAttribute('placeholder') || '') }));
console.log(JSON.stringify({ step:'kb-state', textSample: kb.text.slice(0,500), placeholders: kb.placeholders }));
if (!kb.placeholders.some(p => /Search notes/i.test(p))) throw new Error('Fleet KB search input not visible');
if (errors.length) console.log(JSON.stringify({ step:'browser-console-errors', count: errors.length, sample: errors.slice(0,8) }));
await browser.close();
